### ISSUE TITLE
Missing GridFieldSortableRows

### ISSUE THREAD

**Issue by catharsisjelly** [Cyber-Duck/Silverstripe-Block-Page#1]
Hi there,

Your code seems to use this class `GridFieldSortableRows` which I think is [here](https://github.com/UndefinedOffset/SortableGridField/) I feel that your composer.json file should be requiring this or at least your documentation should.

Happy to put a PR together to fix this but was hoping you could confirm that this is the right codebase

**Comment by Andrew-Mc-Cormack** [comment]
Yeah your right, it requires that plugin. Its been added to composer now, thanks

**Comment by catharsisjelly** [comment]
You're welcome
